version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aip490-be
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 12G 